theme: jekyll-theme-minimal
title: richard4231's homepage
description: under infinite construction...
lsi: false
safe: true
source: /docs/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
